# Foundations of Artificial Intelligence

::: {.callout-note icon="true" collapse="false"}
# Content from TAILOR deliverable report D9.6 

The content of this page is currently a re-formatted copy from the Deliverable
9.6 PhD Curriculum Report.
:::

This topic presents the foundations, scope, history and methodologies of AI.

## Content/Knowledge

Students should be able to:

-   Comprehend and compare the various **definitions of AI**.
-   Understand/describe the **history of AI** and the eras into which it
    can be periodized.
-   Properly **position AI within computer science** and analyse its
    links with other fields of science or philosophy (neuroscience,
    philosophy of mind, electrical/electronic engineering,
    mathematics, cognitive science).
-   Understand and historically order the most important **propositions
    in the philosophy of AI** (e.g., Turing test, physical symbol
    system hypothesis, etc.).
-   Comprehend the specific **relationship of AI** with logic, applied
    maths, game theory and other areas of mathematics.
-   Compare and discriminate between different **AI methodological
    paradigms** (symbolic, computational, etc.).
-   Understand/describe the concept of the **intelligent agent**.

## Methodological/Skills

Students should be able to:

-   Apply their critical and analytical faculties, in order to argue
    about the comparative advantages/disadvantages of different
    methodological paradigms from the rich history of AI.
-   Clearly argue about similarities and differences between
    natural/human intelligence and artificial intelligence, given the
    current level of technological progress and potential near-future
    advances.

## Transferrable/Application

Students should be able to:

-   Work effectively with others in an interdisciplinary and/or
    international team.
-   Clearly and succinctly communicate their ideas to technical and
    non-technical audiences.

