# Reasoning and Learning in Social Contexts

::: {.callout-note icon="true" collapse="false"}
# Content from TAILOR deliverable report D9.6 

The content of this page is currently a re-formatted copy from the Deliverable
9.6 PhD Curriculum Report.
:::

This topic covers the foundations, techniques, algorithms and tools for
allowing autonomous AI agents to be social and act within societies. It will
offer a breadth of understanding in technologies that allow building Social AI
systems and a multidisciplinary take on this topic that will impact every
aspect of our daily life in the future.

## Content/Knowledge

Students should be able to:

-   Comprehend that capturing the social aspects of human behaviour is
    essential in understanding **how people think and how people react
    to each other**, which is a fundamental step to developing
    reasoning algorithms that can operate effectively in social
    contexts.
-   Demonstrate a good **understanding of computational models of social
    reality**. That is, how social contexts determine human behaviour
    through norms, practices, conventions, rituals and other rules of
    human social nature.
-   Understand current methodologies to model social cognition,
    collaboration and teamwork.
-   Understand /describe theoretical models for cooperation between
    agents. 
-   Understand the process of creating systems equipped **with
    perception and social capabilities** that allows them to adapt to
    different social contexts and **learn from other agents** in such
    environments.
-   Understand how models of social reality generate emergent behaviour
    and the impact of such models in agent societies and social
    networks of multi-agent systems. 

## Methodological/Skills

Students should be able to:

-   Correctly identify different ways to sense the environment and
    understand how to use off-the-shelf solutions and how to make
    sense of the captured data.
-   Explore the creation of a simple Social AI System, using a
    perception technology whose data feeds into a reasoning mechanism
    that outputs social (and intelligent) acts in a context of choice.
-   Evaluate social reasoning and learning algorithms in the form of
    simulations or with a human.
-   Analyse the solutions to a problem and critically think about the
    societal impact.

## Transferrable/Application

Students should be able to:

-   Work effectively with others in an interdisciplinary and/or
    international team.
-   Design and manage individual projects.
-   Clearly and succinctly communicate their ideas to technical
    audiences.

