project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!venv/"
    - "!inprogress/"

website:
  title: "Foundations of Trustworthy AI"
  reader-mode: true
  site-url: https://tailor-uob.github.io/mooc_trustworthy_ai/
  repo-url: https://github.com/TAILOR-UoB/mooc_trustworthy_ai
  repo-branch: main
  repo-actions: [edit, issue]

  sidebar:
    style: "docked"
    search: true
    logo: "./images/TAILOR-MOOC-tai.svg"
    collapse-level: 2
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/TAILOR-UoB/mooc_trustworthy_ai
          - text: Report a Bug
            href: https://github.com/TAILOR-UoB/mooc_trustworthy_ai/issues/new?labels=bug
    contents:
      - href: index.qmd
        text: Home
      - href: 0_foundations_of_ai.qmd
      - section: 1_foundations_of_tai.qmd
        contents:
          - cha_wahcc/wahcc.qmd
          - cha_odm/odm.qmd
      - href: 2_ai_paradigms_representations.qmd
      - href: 3_deciding_learning_how_act.qmd
      - href: 4_reasoning_learning_social_context.qmd
      - href: 5_automated_ai.qmd

  page-footer:
    left: |
      Foundations of Trustworthy AI was written by Miquel Perello Nieto based on the TAILOR PhD Curriculum and other sources.
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.
  #cover-image: "images/TAILOR-MOOC-tai.svg"
  favicon: cropped-tailor-logo-symbol-32x32.png
  #downloads: [pdf, epub]

format:
    # pdf:
    #   documentclass: scrbook
    #   papersize: a4
    #   toc: true
    #   toc-depth: 2
    #   toc-title: "Contents"
    #   number-sections: true
    #   number-detph: 2
    #   cite-method: biblatex
  html:
    theme:
      light: [yeti, mooctai.scss]
      dark: [superhero, mooctai_dark.scss]
    code-link: true
    css: style.css
    toc: true
    number-chapters: true
    number-depth: 2
    page-layout: full
    grid:
      sidebar-width: 350px
    html-math-method: katex
    author-meta: "Miquel Perello Nieto"
    tbl-cap-location: bottom
    fig-cap-location: bottom
    shift-heading-level-by: 1
    code-line-numbers: true
    fig-format: svg
    fig-responsive: true
    callout-appearance: simple
    header-includes: |
      <link rel="stylesheet" media="screen" href="/fonts/Myriad Pro Regular.ttf" type="text/css"/>

contrastcolor: "#37BEED"
link-color: "#37BEED"
editor: visual
jupyter: python3
exclude_patterns:
  - .DS_Store
  - .git
  - .github
  - .gitignore
  - .nojekyll
