project:
  type: website

website:
  title: "Foundations of Trustworthy AI"
  reader-mode: true
  site-url: https://tailor-uob.github.io/mooc_trustworthy_ai/
  repo-url: https://github.com/TAILOR-UoB/mooc_trustworthy_ai
  repo-branch: main
  repo-actions: [edit, issue]

  sidebar:
    style: "docked"
    search: true
    logo: "TAILOR logo - full-color rgb.svg"
    collapse-level: 1
    contents:
      - index.qmd
      - intro.qmd
      - section: explainable-ai-systems.qmd
        contents:
          - cha_wahcc/wahcc.qmd
          - cha_odm/odm.qmd

  page-footer:
    left: |
      Foundations of Trustworthy AI was written by Miquel Perello Nieto by compiling multiple information from the TAILOR project.
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.
  #cover-image: "images/TAILOR-MOOC-tai.svg"
  favicon: cropped-tailor-logo-symbol-32x32.png
  #downloads: [pdf, epub]

format:
    #pdf:
    #  documentclass: scrbook
    #  fontfamily: libertinus
    #  papersize: a4
    #  toc: true
    #  toc-depth: 2
    #  toc-title: "Contents"
    #  number-sections: true
    #  number-detph: 2
    #  cite-method: biblatex
  html:
    theme:
      light: [yeti, mooctai.scss]
      dark: [superhero, mooctai_dark.scss]
    code-link: true
    css: style.css
    toc: true
    page-layout: full
    grid:
      sidebar-width: 500px
    html-math-method: katex
    number-depth: 2
    author-meta: "Miquel Perello Nieto"
    tbl-cap-location: bottom
    fig-cap-location: bottom
    shift-heading-level-by: 1
    code-line-numbers: true
    fig-format: svg
    fig-responsive: true
    callout-appearance: simple
    header-includes: |
      <link rel="stylesheet" media="screen" href="/fonts/Myriad Pro Regular.ttf" type="text/css"/>
  revealjs:
    smaller: true
    scrollable: true
    logo: "images/TAILOR logo - full-color rgb.svg"
    footer: "These slides are part of a MOOC on Trustworthy AI by The TAILOR Network"
    center: true
    slide-number: true
    incremental: true
    number-depth: 2
    slide-level: 3
    show-slide-number: "all"

contrastcolor: "#37BEED"
link-color: "#37BEED"
mainfont: Arial
editor: visual
jupyter: python3
exclude_patterns:
  - .DS_Store
  - .git
  - .github
  - .gitignore
  - .nojekyll
