on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown

          #- name: Install Quarto extensions
          #  run: |
          #    quarto add coatless/quarto-webr
          #    quarto add quarto-ext/shinylive
      
      # add software dependencies here

    - name: Publish to GitHub Pages 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site/
        CLEAN: true

        #- name: Publish to GitHub Pages (and render)
        #  uses: quarto-dev/quarto-actions/publish@v2
        #  with:
        #    target: gh-pages
        #  env:
        #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
